version: '3.8'

services:
  express-api:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm run server"
    environment:
      - PORT=8081
      - CHOKIDAR_USEPOLLING=true